In [1]:
import pandas as pd
import numpy as np
from PIL import Image, ImageStat
import os

In [2]:
column_names = ["Name", "Description", "Image_ID", "Width", "Height", "Averege_Color", "Median", "x_Brightest", "y_Brightest"]

In [3]:
df = pd.DataFrame(columns = column_names)

In [4]:
cwd = os.getcwd() 
cwd
os.chdir(f"{cwd}\\images")

In [5]:
def find_coords(val):
    for k in range(grayscale_im.size[0]):   
       for j in range(grayscale_im.size[1]):  
          if np.array(pixel_arr[k,j]) == val:
                return [k, j];

In [6]:
j = 0;
for f in os.listdir('.'):
    i = Image.open(f)
    fn, fext = os.path.splitext(f)
    #i.filename, i.size, " ".join(fn.split('-'))
    #pixel_arr = np.array(i)
    #sum1 = np.sum(pixel_arr, axis=0)
    #sum1 = np.sum(sum1, axis=0)
    #avg_color = tuple((sum1 / (pixel_arr.size / sum1.size)).astype(int))
    #print(avg_color)
    
    avg_color = tuple(np.array(ImageStat.Stat(i).mean).astype(int))
    print(avg_color)
    
    grayscale_im = i.convert('L')
    pixel_arr = np.array(grayscale_im)
    
    #median
    med = ImageStat.Stat(grayscale_im).median[0]
    print(med)
    
    min_max = grayscale_im.getextrema()
    print(min_max)
    
    coords = find_coords(min_max[1]);
    print(coords);
    j = j + 1;
    df.loc[f'{j}'] = [f"{i.filename}", f"{' '.join(fn.split('-')[:-1])}", f"{fn.split('-')[-1]}", f"{i.size[0]}", f"{i.size[1]}",
          f"{avg_color}", f"{med}", f"{coords[0]}", f"{coords[1]}"]
    

df.head()

(156, 164, 158)
194
(6, 255)
[1031, 81]
(105, 96, 89)
77
(14, 255)
[32, 899]
(161, 170, 188)
190
(7, 255)
[728, 440]
(150, 159, 172)
184
(0, 255)
[57, 834]
(35, 72, 56)
52
(3, 255)
[314, 977]
(208, 156, 33)
176
(13, 255)
[1031, 81]
(173, 153, 121)
161
(0, 255)
[0, 621]
(82, 89, 102)
61
(0, 255)
[113, 426]
(217, 170, 172)
255
(19, 255)
[0, 0]
(90, 102, 109)
77
(8, 255)
[1031, 81]
(65, 68, 116)
46
(18, 255)
[1031, 81]
(191, 137, 156)
164
(24, 255)
[690, 80]
(79, 97, 104)
86
(0, 255)
[510, 686]
(127, 165, 187)
161
(45, 255)
[845, 960]
(52, 63, 83)
48
(0, 255)
[186, 714]
(207, 200, 189)
236
(38, 255)
[0, 4]
(32, 44, 53)
35
(0, 255)
[875, 80]
(60, 61, 61)
46
(0, 255)
[32, 872]
(184, 165, 150)
186
(0, 255)
[0, 90]
(47, 64, 81)
46
(0, 255)
[90, 317]

,Name,Description,Image_ID,Width,Height,Averege_Color,Median,x_Brightest,y_Brightest
1,stock-photo-adult-and-child-hands-holding-red-...,stock photo adult and child hands holding red ...,1487364161,1500,1101,"(156, 164, 158)",194,1031,81
2,stock-photo-architect-team-having-a-discussion...,stock photo architect team having a discussion,1380294050,1500,945,"(105, 96, 89)",77,32,899
3,stock-photo-close-up-of-two-businessmen-shakin...,stock photo close up of two businessmen shakin...,1452180959,1500,1101,"(161, 170, 188)",190,728,440
4,stock-photo-close-up-top-view-of-young-busines...,stock photo close up top view of young busines...,1498583432,1500,940,"(150, 159, 172)",184,57,834
5,stock-photo-closeup-view-of-woman-with-drawn-f...,stock photo closeup view of woman with drawn f...,1508523470,1500,1101,"(35, 72, 56)",52,314,977

In [7]:
df.to_csv("../images.csv", index=False)